version: "3"
services:
  postgres-spring:
    container_name: postgres-spring
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - /Users/mateusnascimento/Documents/java/snack-bars/data/postgres:/Users/mateusnascimento/Documents/java/snack-bars/data/postgres
    networks:
      - postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=snackbars

  pgadmin-spring:
    links:
      - postgres-spring:postgres-spring
    container_name: pgadmin-spring
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /Users/mateusnascimento/Documents/java/snack-bars/data/pgadmin:/root/.pgadmin
    networks:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  postgres:
    driver: bridge