# fly.toml file generated for snackbars-app on 2023-01-09T21:27:53-03:00

app = "snackbars-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  _JAVA_OPTIONS="-XX:MaxRAM=70m"
  SPRING_PROFILES_ACTIVE="prod,api-docs"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED="false"
  SPRING_DATASOURCE_USERNAME="postgres"
  SPRING_DATASOURCE_PASSWORD="DSDt8E6hxuVZDrj"
  SPRING_DATASOURCE_URL="jdbc:postgresql://snackbars-postgres.internal:5432/snackbars"
  SPRING_LIQUIBASE_URL="jdbc:postgresql://snackbars-postgres.internal:5432/snackbars"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

#  [[services.http_checks]]
#    grace_period = "1s"
#    interval = 5000
#    path = "/"
#    protocol = "http"
#    restart_limit = 0
#    timeout = 2000
#    tls_skip_verify = false
#    [services.http_checks.headers]